### ISSUE TITLE
Rename the repo to device-plugins

### ISSUE THREAD

**Issue by fabiand** [mpolednik/linux-vfio-k8s-dpi#1]
You might want to renmae this repo to device-plugins or a like, then we could move it to the kubevirt repo, and use it as the cnetrla repo for all kubevirt related dev plugins.

**Comment by mpolednik** [comment]
@fabiand I'm thinking something like "kubernetes-device-plugins" (because device-plugins might conflict with something I'd start in the future).

**Comment by fabiand** [comment]
Works for me

**Comment by mpolednik** [comment]
Renamed.
