### ISSUE TITLE
Bridge DP waits forever for failed pods

### ISSUE THREAD

**Issue by phoracek** [mpolednik/linux-vfio-k8s-dpi#13]
When pod deployment fails in the middle (after resource was allocated), bridge device plugin waits for it to appear forever.

This problem is related to the temporary netns-access hack, do we want to fix it?

**Comment by mpolednik** [comment]
@phoracek We need to be as robust as possible - there are too many things that will go wrong with device plugins. Since Kubernetes doesn't currently set a timeout, having a reasonable one would be great.

**Comment by fabiand** [comment]
For now - What about a simple timeout?
This logarthimic retrial mechanism that kbe uses ..

**Comment by phoracek** [comment]
Should be fixed by https://github.com/kubevirt/kubernetes-device-plugins/pull/15
