### ISSUE TITLE
The plugins are missing tests

### ISSUE THREAD

**Issue by mpolednik** [mpolednik/linux-vfio-k8s-dpi#14]
Currently, there are no tests for the plugin themselves and only simple test for manager. This should be our top priority, as having untested code handle devices in the system is extremely dangerous.

General ideas:

* let's consider gomega/ginkgo for BDD (depends on setup/teardown complexity compared to gotest)
* mock Kubelet's device plugin gRPC API to have properly tested manager code
* have unit + functional tests of the plugins (subject to hw requirements)

**Comment by mpolednik** [comment]
CC @phoracek as networking will be I suppose the most difficult to keep tested.

**Comment by fabiand** [comment]
As logn as the plugins are single node you can consider:

https://kinvolk.io/blog/2017/10/running-kubernetes-on-travis-ci-with-minikube/

**Comment by phoracek** [comment]
I feel like it would be easier to create functional tests than mocking for most of it.

**Comment by mpolednik** [comment]
The minikube-on-travis looks beautiful - looking into having that. @phoracek they would, but we need need something a) simple enough for make test, b) complex functional suite c) CI compatible tests.

**Comment by yuvalif** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [add integration tests to network bridge device plugin](https://trello.com/c/hVdilLJK/119-add-integration-tests-to-network-bridge-device-plugin)
