### ISSUE TITLE
Does kvm DP need /dev and /sys and /lib/modules

### ISSUE THREAD

**Issue by fabiand** [mpolednik/linux-vfio-k8s-dpi#26]
The kvm readme states that host sys and lib/modules are needed. Id oubt this :)

host should definetly not be passed in, as this is what the DP is for to solve: toget something into the pod (dev/kvm in this case) if it's not there.

sys and lib/modules - I don#t see a reason. what are the reasons?

**Comment by rmohr** [comment]
I can only say that on `kubevirt/kubevirt`, we have no host sys and lib directory mounted. It works for us. Did also not see a requirement like that in other kvm hooks (like e.g. https://github.com/stefwalter/oci-kvm-hook).

**Comment by fabiand** [comment]
In the KubeVirt launcher container the reason for /sys and /dev and lib/modules is libvirt, which is somehow using these directories (direct or indirect).

In this bug I just wonder if this code has a direct raltionship to any of tehse directories, but it seems it doesnt.

**Comment by rmohr** [comment]
> In the KubeVirt launcher container the reason for /sys and /dev and lib/modules is libvirt, which is somehow using these directories (direct or indirect).

I think we misunderstood us here. Since yesterday we don't mount any of those directories (even with libvirt), so to use /dev/kvm you don't need anything from the host if you create /dev/kvm with mknod, or directly mount only that device in.

**Comment by fabiand** [comment]
Ah yes, so true. Good that you point it out :) I actually wonder if we'll see some fallout. Great for now.
