### ISSUE TITLE
do interface cleanup when pod is terminating

### ISSUE THREAD

**Issue by yuvalif** [mpolednik/linux-vfio-k8s-dpi#36]
instead of auto-generating a random nic name, it should consist of a hash of the pod name, this name should be used by the plugin as the pod goes down to cleanup the nic

**Comment by phoracek** [comment]
Correct me if I'm wrong, but I believe there is not need for a cleanup.
When namespace with virtual interface is deleted, it removes also the
interface. In case of physical interfaces, it removes IP configuration,
aliases, etc.

Dne ne 1. 7. 2018 9:24 uživatel Yuval Lifshitz <notifications@github.com>
napsal:

**Comment by yuvalif** [comment]
i tried that. the interface inside the pod is deleted, but the nic_xxx with the random name remains.

**Comment by fabiand** [comment]
I wonder if https://godoc.org/github.com/vishvananda/netlink#LinkSubscribe or https://godoc.org/github.com/vishvananda/netlink#AddrSubscribeAt could actually help us in the DP to detect when an interface will be freed - in order to do cleanups.

**Comment by yuvalif** [comment]
@fabiand will try it. probably better than subscribing to pod changes

**Comment by fabiand** [comment]
@yuvalif +1 - that would also be **really** interesting to let upstream know. Because cleanup is an issue.

**Comment by fabiand** [comment]
Besides that we can consider to keep some state informations somewhere (hostPath?) to also recover if a DP crashes.

**Comment by phoracek** [comment]
tackled in https://github.com/kubevirt/kubernetes-device-plugins/pull/41

**Comment by yuvalif** [comment]
@fabiand when device plugin is removed, all of the devices it created are cleaned up. So, for that, no need to store data. Not sure what happens if the device plugin pod crashes and restart?

**Comment by phoracek** [comment]
@yuvalif I wonder how that could happen. DP works in host network namespace and there should be no connection to interfaces it created, right?

**Comment by fabiand** [comment]
I think there are several cases to consider:

1. host interface moved to target NS
2. veth with endpoints in host NS and target NS

For both cases we need to ask what happens with the interfaces (both ends if there) in case the target NS goes away.

**Comment by phoracek** [comment]
Physical host interface should be moved back to host netns, its
configuration stripped down, IP is not kept and alias is removed as far as
I remember.

Like Yuval said, pod side of veth is removed, host side kept.

**Comment by phoracek** [comment]
Fixed in #50
