### ISSUE TITLE
Auto-reload on configmap change.

### ISSUE THREAD

**Issue by gageorsburn** [mpolednik/linux-vfio-k8s-dpi#49]
We should add functionality to reload whenever the configmap is modified so that the pod doesn't need to be deleted and re-created. Definitely low priority and a quality of life improvement.

**Comment by phoracek** [comment]
Thanks @gageorsburn  for opening this.

This should not be difficult to implement. Instead of passing values from config map as parameters to the bridge DP container, we should introduce config map monitoring in https://github.com/kubevirt/kubernetes-device-plugins/blob/master/pkg/network/bridge/lister.go and just register new list of bridges once the config map is changed.

**Comment by gageorsburn** [comment]
@phoracek Actually more than happy to work on this.

Do you have an example flow for how to contribute? The build process is similar yet has subtle differences from kubevirt. E.g. cluster-sync doesn't start a pod of device plugin.

**Comment by phoracek** [comment]
Great @gageorsburn! `cluster-sync` here only builds the image and pushes it to local cluster registry. Then you can use it there either manually or with a functional test, but for that I'd wait until https://github.com/kubevirt/kubernetes-device-plugins/pull/47 is merged or rebase on top of it.

After you have some code that can be built, start a cluster with it, set config map with initial list of bridges, deploy the plugin and then see what resources are reported in `node.status.allocatable`. You don't even need to create bridges, they should be reported with capacity "0" if not available on the host. Then you can add some bridges into the config map and check allocatables again.

Please let me know if you have any questions :) Thanks a lot

**Comment by gageorsburn** [comment]
@phoracek So there's probably a couple different ways this can be done, but the immediate thought that comes to mind is what if the configmap were mounted as a file instead of an environment variable? 

A couple of benefits to this would be 
- we could watch the file system for changes instead of needing to add in more integrations for fetching configmaps
- we could make the configmap more structured with say like yaml compared to splitting strings on `,`

**Comment by phoracek** [comment]
@gageorsburn I did not know you that the mounted config file is changed with its definition. I guess that's one of possible solutions.

But why not just monitor the definition directly on the Kubernetes API? Should be pretty straightforward, just start the monitor with simple callback that will push new list of bridges to Discover channel when edited https://github.com/kubevirt/kubernetes-device-plugins/blob/master/pkg/network/bridge/lister.go#L37.

**Comment by gageorsburn** [comment]
@phoracek Yeah Kubernetes updates the file in the mounted volume. 

We could go that route as well but I believe, and correct me if I'm wrong but we could need a service account with permissions to fetch config maps. The default service account in a pod doesn't have permissions. 

```
panic: configmaps is forbidden: User "system:serviceaccount:default:default" cannot list configmaps in the namespace "default"

goroutine 1 [running]:
main.main()
	/go/src/github.com/gageorsburn/app/main.go:28 +0x1f9
```

Which looks to be fine as long as pod is running in `kube-system` namespace. So yeah I guess I'll do that route, should be pretty easy.

**Comment by ahmadiq** [comment]
@gageorsburn Please take a look at this tool that my team has built and opensourced: [Reloader](https://github.com/stakater/Reloader). I'm hoping it fits your requirement.

[Reloader](https://github.com/stakater/Reloader) watches changes in ConfigMap and Secret and updates the associated Deployments, Daemonsets and Statefulsets, based on the configured update strategy. We are also using it in production clusters of our customers.

**Comment by gageorsburn** [comment]
There's a kubernetes API to watch for updates.

**Comment by ahmadiq** [comment]
Yes Reloader uses the Kubernetes API to watch for updates to configmaps and secrets, and triggers an update for the resources that are annotated for reload.

**Comment by rmohr** [comment]
Btw. if you want to avoid the need for a service account, you can use the downwards API to map the config map into a file on the fileystem. Your binary needs to be able to detect file changes then (e.g. inotify). The kubelet periodically updates modfied configMaps if you bind the configmap via a volume.

**Comment by phoracek** [comment]
@ahmadiq thanks for suggestion, but I think it is better to keep it minimal here.

@rmohr yea, @gageorsburn suggested it in the beggining. I think it is reasonable to keep network plugin under kube-system namespace or keep a service account, don't you think?

**Comment by gageorsburn** [comment]
@phoracek Yeah I think it makes the most sense in kube-system. There isn't really a need to have multiple deployments of it unless it's for multi tenancy. It leverages host networking too so I'd say it is more of a "system" pod. 

In regards to #54 is there anything else that needs to be done?

**Comment by khteh** [comment]
Any update on this please? When would this be available? Which release? Thanks.
