### ISSUE TITLE
Go routines which change namespaces need to be locked

### ISSUE THREAD

**Issue by rmohr** [mpolednik/linux-vfio-k8s-dpi#51]
Routines which change namespaces need to be locked:

```go
  func doSomething() {
  runtime.LockOSThread()
  defer runtime.UnlockOSThread()
    # do somehing in here and don't spawn go routines
}
```

also make sure that the code does not compile for go versions older than 1.10. Otherwise there can even issues occur when the thread is locked.

See https://www.weave.works/blog/linux-namespaces-golang-followup for a nice summary.

**Comment by phoracek** [comment]
Thanks a lot @rmohr, will tackle this after/with the cleanup patch.
