### ISSUE TITLE
[READ IF YOU USE THIS] This repository may get archived

### ISSUE THREAD

**Issue by phoracek** [mpolednik/linux-vfio-k8s-dpi#64]
Hello,

in KubeVirt we used to use kubernetes-device-plugins [1] to experiment\
with device plugins to:
- connect pod's to linux bridges
- pass PCI devices to containers
- expose kvm device to containers

The reality is that this repo was not touched (except for some small
adjustments) in the last 2 years. It was used only to host device plugins
used within kubevirt. Is there any reason not to make this
repository read-only? Anybody using it on this forum? If nobody votes
against it in the next two weeks, I will archive the repo (note that it won't
be deleted, just set to read-only and marked as discontinued).

Note that I don't want to archive the device-plugin-manager [1] which
seems to be vendored by folks.

Regards,
Petr

[1] https://github.com/kubevirt/device-plugin-manager

**Comment by maiqueb** [comment]
Hi,

We're looking into this project to set the cgroups for the character device used by macvtap.

**Comment by phoracek** [comment]
Hello @maiqueb. That means you'd need to extend this project with a new DP (I was more afraid somebody is using existing plugins).

I would advice you to create a new repository and use https://github.com/kubevirt/device-plugin-manager as your framework. All this repo adds on top of that is outdated (Go 1.9, Kubernetes 1.10) development infrastructure and some directory structure.

I'd be happy to help you set up your own repo (rather than continue maintaining this old one). Please let me know if that sounds reasonable to you.

**Comment by halkeye** [comment]
I was planning on using it for like octoprint to be able to run the host that had the 3d printer installed.

I can just fork it though if need be.

**Comment by phoracek** [comment]
Hey @halkeye! I'd recommend you the same as to Miguel. This project is not bringing any real benefits, just maintenance burden. I'd recommend you creating your own blank new repo and using the https://github.com/kubevirt/device-plugin-manager. With that you would get minimal up-to-date project, using all the bells and whistles of the device-plugin-manager.

3D printer in Kubernetes? That's so cool! Please lemme know when you have it published ;) BTW, I'd be happy to assist you using the device-plugin-manager, just open issues on the repo.

**Comment by maiqueb** [comment]
@phoracek I think you can archive the repo, and close the issue.

**Comment by phoracek** [comment]
Goodbye repo.
